version: "3.8"

services:
  product-service:
    build:
      context: C:/Users/46768/Documents/ecom/backend/Product
      dockerfile: Dockerfile
    ports:
      - "8181:8181"
    depends_on:
      - product-db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://product-db:5432/productdb
      - SPRING_DATASOURCE_USERNAME=productuser
      - SPRING_DATASOURCE_PASSWORD=productpass

  product-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=productdb
      - POSTGRES_USER=productuser
      - POSTGRES_PASSWORD=productpass
    ports:
      - "5431:5432"

  customer-service:
    build:
      context: C:/Users/46768/Documents/ecom/backend/customer
      dockerfile: Dockerfile
    ports:
      - "8282:8282"
    depends_on:
      - customer-db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://customer-db:5432/customerdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user

  customer-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=customerdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - "5432:5432"

  order-service:
    build:
      context: C:/Users/46768/Documents/ecom/backend/Order
      dockerfile: Dockerfile
    ports:
      - "8383:8383"
    depends_on:
      - order-db
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - SPRING_DATASOURCE_URL=jdbc:postgresql://order-db:5432/orderdb
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=user

  order-db:
    image: postgres:13
    environment:
      - POSTGRES_DB=orderdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=user
    ports:
      - "5433:5432"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" 
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
