name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - Order
          - Product
          - customer
    defaults:
      run:
        working-directory: ./backend/${{ matrix.service }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

     

  frontend:
    runs-on: ubuntu-latest
    needs: backend
    defaults:
      run:
        working-directory: ./frontend/admin-modal
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: frontend-build
          path: ./dist
