name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - name: Print a message
        run: echo "This job has no dependencies."

  backend:
    runs-on: ubuntu-latest
    needs: setup
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: testdb
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpass
        ports:
          - 5431:5432

      rabbitmq:
        image: rabbitmq:3-management
        ports:
          - 5672:5672
          - 15672:15672
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest

    strategy:
      matrix:
        service:
          - Order
          - Product
          - Customer
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: List directory contents
        run: ls -R

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..10}; do
            pg_isready -h localhost -p 5432 -U testuser && break || sleep 5
          done

      - name: Build with Maven
        run: mvn clean install
        working-directory: ./backend/${{ matrix.service }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/docker-practice-repo:${{ matrix.service }}-latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/docker-practice-repo:${{ matrix.service }}-latest
        working-directory: ./backend/${{ matrix.service }}
