name: Test Secret

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Print Secret
        run: |
          echo "The secret is: ${{ secrets.MY_SECRET }}"

      - name: Print MY_VAR
        run: |
          echo "The variable is: $MY_VAR"
        env:
          MY_VAR: ${{ vars.MY_VAR }}
