name: Test Secret

on:
  workflow_dispatch:

jobs:
  test-secrets:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Print Secret (first run will be empty, second run will be masked)
        run: |
          echo "The secret is: ${{ secrets.MY_SECRET }}"
